/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/Theme/index.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle/index.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme/index.vue')['default']
  }
}
